### ISSUE TITLE
whille presing Up button window scroll triggered!

### ISSUE THREAD

**Issue by Srkrishna** [123survesh/tetris#2]

**Comment by 123survesh** [comment]
This issue is occurring when the height of the game board is greater than the window size and a scroll bar appears. I was not able to fix this issue. 

I tried adding `event.preventDefault(); ` thinking that it will prevent the default action of the up key to scroll, but it didn't help as much.

Instead I made the game board responsive to the screen height, 
Reference Commit :https://github.com/123survesh/tetris/commit/14c4964f03e8643f319b21f53b9e27e741b2a94f

The above issue must not be faced now, do check and confirm, I will close the issue.

Thanks :)
